import streamlit as st
import plotly.express as px
import plotly.graph_objects as go
import pandas as pd
from style import (
    inject_css, sidebar_brand, page_header, section_header,
    kpi_card, chart_label, chart_note, insight_card,
    apply_plot_layout, footer, no_data_warning, COLORS, COFFEE_PALETTE,
)
from utils import calculate_kpis

st.set_page_config(page_title="Executive Overview", layout="wide", page_icon="📊")
inject_css()
sidebar_brand("Afficionado Coffee", "Executive Overview")

page_header("Executive Overview", subtitle="Full-spectrum business performance dashboard")

if not (st.session_state.get("df") is not None):
    no_data_warning()
    footer()
    st.stop()

df = st.session_state["df"]

# ── KPIs ──────────────────────────────────────────────────────────────────────
section_header("Key Performance Indicators")
kpis = calculate_kpis(df)
col1, col2, col3, col4 = st.columns(4)
kpi_card(col1, "Total Revenue",      f"${kpis['Revenue']:,.0f}",         icon="💰", color="orange")
kpi_card(col2, "Transactions",       f"{kpis['Transactions']:,}",        icon="🧾", color="blue")
kpi_card(col3, "Units Sold",         f"{kpis['Quantity']:,}",            icon="📦", color="green")
kpi_card(col4, "Avg Order Value",    f"${kpis['Avg_Order_Value']:.2f}",  icon="📈", color="purple")

st.markdown("<br>", unsafe_allow_html=True)
col5, col6 = st.columns(2)
kpi_card(col5, "Best-Performing Store",    kpis["Best_Store"],    icon="🏆", color="gold")
kpi_card(col6, "Top Product Category",     kpis["Best_Category"], icon="🥇", color="rust")


# ── Revenue Trend ─────────────────────────────────────────────────────────────
section_header("Revenue Trends")
chart_label("Daily Revenue Trend", "Total revenue generated each day")

daily_sales = df.groupby("date")["revenue"].sum().reset_index()
daily_sales["date"] = pd.to_datetime(daily_sales["date"])

fig = go.Figure()
fig.add_trace(go.Bar(
    x=daily_sales["date"], y=daily_sales["revenue"],
    marker_color=COLORS["caramel"],
    opacity=0.85,
    hovertemplate="<b>%{x|%b %d}</b><br>$%{y:,.0f}<extra></extra>",
))
fig.update_xaxes(tickformat="%b %d", tickangle=30)
fig.update_yaxes(tickprefix="$", tickformat=",.0f")
apply_plot_layout(fig, height=320)
st.plotly_chart(fig, use_container_width=True)
chart_note(f"Total revenue: ${kpis['Revenue']:,.0f}. Analyze momentum across days to identify high-performance periods.")

# ── Store Performance ──────────────────────────────────────────────────────────
section_header("Store Performance")
chart_label("Revenue by Store", "Total revenue generated by each store location")

col1, col2 = st.columns(2)
with col1:
    store_sales = (
        df.groupby("store_location")["revenue"].sum()
        .reset_index().sort_values("revenue", ascending=False)
    )
    fig = go.Figure(go.Bar(
        x=store_sales["store_location"], y=store_sales["revenue"],
        marker=dict(
            color=store_sales["revenue"],
            colorscale=[[0, COLORS["espresso"]], [0.5, COLORS["brown"]], [1, COLORS["caramel"]]],
            showscale=False,
        ),
        hovertemplate="%{x}<br>$%{y:,.0f}<extra></extra>",
    ))
    fig.update_yaxes(tickprefix="$")
    apply_plot_layout(fig)
    st.plotly_chart(fig, use_container_width=True)
    chart_note(f"Best store: ${store_sales['revenue'].max():,.0f}. Replicate top-store practices network-wide.")

with col2:
    store_txn = (
        df.groupby("store_location")["transaction_id"].nunique()
        .reset_index().sort_values("transaction_id", ascending=False)
    )
    fig = px.pie(
        store_txn, names="store_location", values="transaction_id",
        hole=0.52, color_discrete_sequence=COFFEE_PALETTE,
    )
    fig.update_traces(
        textposition="outside",
        hovertemplate="<b>%{label}</b><br>%{value:,} transactions<extra></extra>",
    )
    apply_plot_layout(fig)
    st.plotly_chart(fig, use_container_width=True)
    chart_note(f"Top store: {store_txn.iloc[0]['store_location']} — {store_txn.iloc[0]['transaction_id']:,} unique transactions.")

# ── Hourly Analysis ────────────────────────────────────────────────────────────
section_header("Hourly Demand Analysis")
chart_label("Transactions by Hour of Day", "Traffic pattern across the 24-hour cycle")

hourly_sales = df.groupby("hour")["transaction_qty"].sum().reset_index()
peak_h = int(hourly_sales.loc[hourly_sales["transaction_qty"].idxmax(), "hour"])
colors_h = [COLORS["caramel"] if h == peak_h else COLORS["espresso"] for h in hourly_sales["hour"]]

fig = go.Figure()
fig.add_trace(go.Scatter(
    x=hourly_sales["hour"], y=hourly_sales["transaction_qty"],
    mode="lines+markers",
    line=dict(color=COLORS["caramel"], width=3),
    marker=dict(
        color=colors_h, size=10,
        line=dict(color=COLORS["caramel"], width=2),
    ),
    hovertemplate="Hour %{x}:00<br>Units: %{y:,}<extra></extra>",
))
fig.update_xaxes(title="Hour of Day", tickmode="linear")
fig.update_yaxes(title="Units Sold", tickformat=",")
apply_plot_layout(fig)
st.plotly_chart(fig, use_container_width=True)
chart_note(f"Peak demand at {peak_h}:00 — ensure full barista coverage and restocked ingredients 30 minutes prior.")

# ── Product Analysis ───────────────────────────────────────────────────────────
col1, col2 = st.columns(2)
with col1:
    section_header("Top Product Categories")
    chart_label("Revenue by Product Category", "Revenue contribution per category")
    cat_sales = (
        df.groupby("product_category")["revenue"].sum()
        .reset_index().sort_values("revenue", ascending=False).head(10)
    )
    fig = px.treemap(
        cat_sales, path=["product_category"], values="revenue",
        color="revenue",
        color_continuous_scale=[[0, COLORS["espresso"]], [0.5, COLORS["brown"]], [1, COLORS["caramel"]]],
    )
    fig.update_traces(hovertemplate="<b>%{label}</b><br>$%{value:,.0f}<extra></extra>")
    apply_plot_layout(fig)
    st.plotly_chart(fig, use_container_width=True)
    chart_note(f"Top category: ${cat_sales['revenue'].max():,.0f}. Focus promotions on high-performing categories.")

with col2:
    section_header("Revenue by Product Type")
    chart_label("Revenue by Product Type", "Total revenue per product type")
    if "product_type" in df.columns:
        type_sales = (
            df.groupby("product_type")["revenue"].sum()
            .reset_index().sort_values("revenue", ascending=False).head(10)
        )
        fig = px.pie(
            type_sales, names="product_type", values="revenue",
            hole=0.52, color_discrete_sequence=COFFEE_PALETTE,
        )
        fig.update_traces(
            textposition="outside",
            hovertemplate="<b>%{label}</b><br>$%{value:,.0f}<extra></extra>",
        )
        apply_plot_layout(fig)
        st.plotly_chart(fig, use_container_width=True)
        chart_note(f"Top type: ${type_sales['revenue'].max():,.0f}. Promoting popular types enhances overall performance.")

# ── Store Ranking Table ────────────────────────────────────────────────────────
section_header("Store Revenue Ranking")
chart_label("Store Ranking by Total Revenue", "All locations sorted by performance")
display_store = store_sales.copy()
display_store.columns = ["Store Location", "Revenue"]
display_store["Revenue"] = display_store["Revenue"].apply(lambda x: f"${x:,.2f}")
st.dataframe(display_store, use_container_width=True, hide_index=True)

# ── Insights ──────────────────────────────────────────────────────────────────
section_header("Insights & Recommendations")

top_pct = store_sales["revenue"].max() / kpis["Revenue"] * 100
insight_card(f"The top store contributes {top_pct:.1f}% of total revenue. Diversify marketing to improve distribution across all locations.", kind="success")
insight_card(f"Demand peaks at {peak_h}:00 — adjust staffing and inventory buffers to maximize revenue during this critical window.", kind="info")
insight_card(f"The leading product category drives significant revenue. Expanding its seasonal range could further accelerate growth.", kind="warning")
footer()
