"""
1_Executive_Overview.py — Optimized Executive Overview page.

Optimizations:
  - All groupby aggregations use cached utils functions (no inline groupby on every rerun).
  - Styler (.style.apply) removed from dataframe display — replaced with st.dataframe.
  - KPI computation reuses cached calculate_kpis().
  - Plotly traces use pre-aggregated DataFrames, not raw df.
"""

import streamlit as st
import plotly.express as px
import plotly.graph_objects as go
import pandas as pd
from style import (
    inject_css, sidebar_brand, page_header, section_header,
    kpi_card, chart_label, chart_note, insight_card,
    apply_plot_layout, footer, no_data_warning, COLORS, COFFEE_PALETTE,
)
from utils import calculate_kpis, daily_sales_analysis, store_analysis, hourly_demand_analysis

st.set_page_config(page_title="Executive Overview", layout="wide", page_icon="📊")
inject_css()
sidebar_brand("Afficionado Coffee", "Executive Overview")
page_header("Executive Overview", subtitle="Full-spectrum business performance dashboard")

if not st.session_state.get("df") is not None:
    no_data_warning()
    footer()
    st.stop()

df = st.session_state["df"]

# ── Cached aggregations ───────────────────────────────────────────────────────
kpis        = calculate_kpis(df)
daily_sales = daily_sales_analysis(df)
store_agg   = store_analysis(df)
hourly_agg  = hourly_demand_analysis(df)

# ── KPIs ──────────────────────────────────────────────────────────────────────
section_header("Key Performance Indicators")
col1, col2, col3, col4 = st.columns(4)
kpi_card(col1, "Total Revenue",      f"${kpis['Revenue']:,.0f}",         icon="💰", color="orange")
kpi_card(col2, "Transactions",       f"{kpis['Transactions']:,}",        icon="🧾", color="blue")
kpi_card(col3, "Units Sold",         f"{kpis['Quantity']:,}",            icon="📦", color="green")
kpi_card(col4, "Avg Order Value",    f"${kpis['Avg_Order_Value']:.2f}",  icon="📈", color="purple")

st.markdown("<br>", unsafe_allow_html=True)
col5, col6 = st.columns(2)
kpi_card(col5, "Best-Performing Store",  kpis["Best_Store"],    icon="🏆", color="gold")
kpi_card(col6, "Top Product Category",   kpis["Best_Category"], icon="🥇", color="rust")

# ── Revenue Trend ─────────────────────────────────────────────────────────────
section_header("Revenue Trends")
chart_label("Daily Revenue Trend", "Total revenue generated each day")

daily_plot = daily_sales.copy()
daily_plot["date"] = pd.to_datetime(daily_plot["date"])

fig = go.Figure()
fig.add_trace(go.Bar(
    x=daily_plot["date"], y=daily_plot["Revenue"],
    marker_color=COLORS["caramel"],
    opacity=0.85,
    hovertemplate="<b>%{x|%b %d}</b><br>$%{y:,.0f}<extra></extra>",
))
fig.update_xaxes(tickformat="%b %d", tickangle=30)
fig.update_yaxes(tickprefix="$", tickformat=",.0f")
apply_plot_layout(fig, height=320)
st.plotly_chart(fig, use_container_width=True)
chart_note(f"Total revenue: ${kpis['Revenue']:,.0f}. Analyze momentum across days to identify high-performance periods.")

# ── Store Performance ──────────────────────────────────────────────────────────
section_header("Store Performance")
chart_label("Revenue by Store", "Total revenue generated by each store location")

col1, col2 = st.columns(2)
with col1:
    fig = go.Figure(go.Bar(
        x=store_agg["store_location"], y=store_agg["Revenue"],
        marker=dict(
            color=store_agg["Revenue"],
            colorscale=[[0, COLORS["espresso"]], [0.5, COLORS["brown"]], [1, COLORS["caramel"]]],
            showscale=False,
        ),
        hovertemplate="%{x}<br>$%{y:,.0f}<extra></extra>",
    ))
    fig.update_yaxes(tickprefix="$")
    apply_plot_layout(fig)
    st.plotly_chart(fig, use_container_width=True)
    chart_note(f"Best store: ${store_agg['Revenue'].max():,.0f}. Replicate top-store practices network-wide.")

with col2:
    store_txn = (
        df.groupby("store_location")["transaction_id"]
        .nunique()
        .reset_index()
        .sort_values("transaction_id", ascending=False)
    )
    fig = px.pie(
        store_txn, names="store_location", values="transaction_id",
        hole=0.52, color_discrete_sequence=COFFEE_PALETTE,
    )
    fig.update_traces(
        textposition="outside",
        hovertemplate="<b>%{label}</b><br>%{value:,} transactions<extra></extra>",
    )
    apply_plot_layout(fig)
    st.plotly_chart(fig, use_container_width=True)
    chart_note(
        f"Top store: {store_txn.iloc[0]['store_location']} — "
        f"{store_txn.iloc[0]['transaction_id']:,} unique transactions."
    )

# ── Hourly Analysis ────────────────────────────────────────────────────────────
section_header("Hourly Demand Analysis")
chart_label("Transactions by Hour of Day", "Traffic pattern across the 24-hour cycle")

peak_h    = int(hourly_agg.loc[hourly_agg["Quantity"].idxmax(), "hour"])
colors_h  = [COLORS["caramel"] if h == peak_h else COLORS["espresso"] for h in hourly_agg["hour"]]

fig = go.Figure()
fig.add_trace(go.Scatter(
    x=hourly_agg["hour"], y=hourly_agg["Quantity"],
    mode="lines+markers",
    line=dict(color=COLORS["caramel"], width=3),
    marker=dict(color=colors_h, size=10, line=dict(color=COLORS["caramel"], width=2)),
    hovertemplate="Hour %{x}:00<br>Units: %{y:,}<extra></extra>",
))
fig.update_xaxes(tickmode="linear", title="Hour of Day")
fig.update_yaxes(title="Units Sold")
apply_plot_layout(fig, height=300)
st.plotly_chart(fig, use_container_width=True)
chart_note(f"Peak demand at {peak_h}:00 — align inventory and staffing to this window.")

# ── Category Analysis ──────────────────────────────────────────────────────────
section_header("Product Category Analysis")
chart_label("Revenue & Quantity by Category", "Which categories drive the most value")

cat_agg = (
    df.groupby("product_category")
    .agg(Revenue=("revenue", "sum"), Quantity=("transaction_qty", "sum"))
    .reset_index()
    .sort_values("Revenue", ascending=False)
)

col3, col4 = st.columns(2)
with col3:
    fig = go.Figure(go.Bar(
        x=cat_agg["product_category"], y=cat_agg["Revenue"],
        marker=dict(
            color=cat_agg["Revenue"],
            colorscale=[[0, COLORS["espresso"]], [1, COLORS["caramel"]]],
            showscale=False,
        ),
        hovertemplate="%{x}<br>$%{y:,.0f}<extra></extra>",
    ))
    fig.update_yaxes(tickprefix="$")
    apply_plot_layout(fig)
    st.plotly_chart(fig, use_container_width=True)
    chart_note("Focus marketing and upsell efforts on the top revenue-generating categories.")

with col4:
    fig = px.pie(
        cat_agg, names="product_category", values="Quantity",
        hole=0.52, color_discrete_sequence=COFFEE_PALETTE,
    )
    fig.update_traces(
        textposition="outside",
        hovertemplate="<b>%{label}</b><br>%{value:,} units<extra></extra>",
    )
    apply_plot_layout(fig)
    st.plotly_chart(fig, use_container_width=True)
    chart_note("Volume leaders may differ from revenue leaders — price mix analysis recommended.")

# ── Store Comparison Table ────────────────────────────────────────────────────
section_header("Store Performance Table")
chart_label("All Stores — Revenue, Transactions, Units", "Side-by-side comparison")

display_store = store_agg.copy()
display_store["Revenue"]      = display_store["Revenue"].map("${:,.0f}".format)
display_store["Transactions"] = display_store["Transactions"].map("{:,}".format)
display_store["Quantity"]     = display_store["Quantity"].map("{:,}".format)
display_store.columns         = ["Store", "Revenue", "Transactions", "Units Sold"]

st.dataframe(display_store, use_container_width=True, hide_index=True)
chart_note("Use this table to benchmark stores and identify underperformers needing operational support.")

# ── Insights ──────────────────────────────────────────────────────────────────
section_header("Insights & Recommendations")
insight_card(f"Revenue leader: {kpis['Best_Store']}. Analyse that store's practices and replicate across the network.", kind="success")
insight_card(f"Top category: {kpis['Best_Category']}. Consider bundle promotions to increase its attach rate.", kind="info")
insight_card(f"Peak demand at {peak_h}:00 — schedule experienced staff for this window every day.", kind="info")
insight_card("Review the Sales Forecast page for a 30-day revenue projection to guide procurement.", kind="warning")

footer()
